export const siteConfig = {
  name: "Matt Pantaleone — AI Engineer & Automation",
  description: "We build AI systems that eliminate expensive manual work: AI agents, workflow automation, AI integration, and custom AI software for businesses.",
  url: "https://pantaleone.net",
  // CHANGED: Points to the dynamic route generated by opengraph-image.tsx
  ogImage: "https://pantaleone.net/opengraph-image", 
  metadataBase: new URL("https://pantaleone.net"),
  keywords: [  "Matt Pantaleone",
  "Pantaleone Digital Services",
  "Forward Deployed AI",
  "AI Engineer",
  "AI Automation",
  "Enterprise AI Workflows",
  "Autonomous Agents",
  "LLM Integration",
  "AI Strategy Consulting",
  "Rapigent",
  "AICEO",
  "Next.js AI",
  "TypeScript",
  "N8N Workflows",
  "RAG Pipelines",
  "Workflow Automation",
  "AI Tools",],
  links: {
    twitter: "https://twitter.com/m_pantaleone",
    github: "https://github.com/pantaleone-ai",
    linkedin: "https://linkedin.com/in/m_pantaleone",
  },
};

export type SiteConfig = typeof siteConfig;
