export const siteConfig = {
  name: "Pantaleone AI",
  description: "Senior AI and Automation Engineer",
  url: "https://pantaleone.net",
  // CHANGED: Points to the dynamic route generated by opengraph-image.tsx
  ogImage: "https://pantaleone.net/opengraph-image", 
  metadataBase: new URL("https://pantaleone.net"),
  keywords: ["Next.js", "React", "AI", "Systems Architecture"],
  links: {
    twitter: "https://twitter.com/pantaleone_ai",
    github: "https://github.com/pantaleone-ai",
    linkedin: "https://linkedin.com/in/pantaleone",
  },
};

export type SiteConfig = typeof siteConfig;