/**
 * 30-day portfolio content calendar (32 posts, ~1/day).
 * Weighted to Tier 1. Every row has hook, CTA, destination, campaign/creative,
 * and recommended visual. No invented stats, testimonials, or pricing.
 * Campaign: [APP]_[PLATFORM]_[OBJECTIVE]_[AUDIENCE]_[GEO]_[YYYYMM]
 * Creative: [APP]_[CONCEPT]_[FORMAT]_[VARIANT]
 */

export type CalendarPost = {
  contentId: string;
  appId: string;
  platform: string;
  contentType: string;
  pillar: string;
  topic: string;
  hook: string;
  body: string;
  cta: string;
  destinationUrl: string;
  campaignId: string;
  creativeId: string;
  publishAt: string;
  priority: "p1" | "p2" | "p3";
  audience: string;
  creative: string;
  objective: string;
  sourceAsset: string;
};

const U = (base: string, source: string, campaign: string, content: string) =>
  `${base}?utm_source=${source}&utm_medium=organic_social&utm_campaign=${campaign}&utm_content=${content}`;

function post(p: CalendarPost): CalendarPost {
  return { ...p, destinationUrl: U(p.destinationUrl, p.platform, p.campaignId, p.creativeId) };
}

export const CALENDAR_30D: CalendarPost[] = [
  post({
    contentId: "syn-pin-drop-01",
    appId: "synthetic-pics",
    platform: "pinterest",
    contentType: "pin",
    pillar: "discovery",
    topic: "New artwork drop",
    hook: "New drop: deep indigo abstract for calm rooms.",
    body: "Human-guided generative piece. See detail crops and room context in the gallery.",
    cta: "Explore the gallery",
    destinationUrl: "https://www.synthetic.pics",
    campaignId: "SYN_PINT_DISCOVERY_ARTBUYERS_US_202610",
    creativeId: "SYN_DROP_PIN_V1",
    publishAt: "2026-10-06T14:00:00Z",
    priority: "p1",
    audience: "Art buyers",
    creative: "1000x1500 pin, artwork hero plus detail crop",
    objective: "Gallery visit and save",
    sourceAsset: "Gallery artwork page",
  }),
  post({
    contentId: "p3d-pin-model-01",
    appId: "print3dmodels",
    platform: "pinterest",
    contentType: "pin",
    pillar: "product",
    topic: "Model drop for desks",
    hook: "New print: geometric planter for small desks.",
    body: "Printed to order and shipped. See dimensions and finish options on the product page.",
    cta: "Shop the print",
    destinationUrl: "https://www.print3dmodels.com",
    campaignId: "P3D_PINT_PURCHASE_GIFTBUYERS_US_202610",
    creativeId: "P3D_PLANTER_PIN_V1",
    publishAt: "2026-10-07T14:00:00Z",
    priority: "p1",
    audience: "Gift buyers",
    creative: "1000x1500 pin, product on desk plus close-up",
    objective: "Product page visit",
    sourceAsset: "Product page",
  }),
  post({
    contentId: "mix-pin-recipe-01",
    appId: "mixphd",
    platform: "pinterest",
    contentType: "pin",
    pillar: "education",
    topic: "My Bar match recipe",
    hook: "Have gin and lemon? Make this in 3 minutes.",
    body: "Recipe uses what is on hand. My Bar matching shows substitutes.",
    cta: "Read the recipe",
    destinationUrl: "https://www.mixphd.com",
    campaignId: "MIX_PINT_TRAFFIC_HOMEBAR_US_202610",
    creativeId: "MIX_GINLEMON_PIN_V1",
    publishAt: "2026-10-08T21:00:00Z",
    priority: "p1",
    audience: "Home bartenders",
    creative: "1000x1500 recipe card with ingredients",
    objective: "Recipe visit and save",
    sourceAsset: "Recipe page",
  }),
  post({
    contentId: "pro-x-fix-01",
    appId: "proswing",
    platform: "x",
    contentType: "x-post",
    pillar: "education",
    topic: "One swing fix",
    hook: "Casting hands? Keep the back elbow connected through contact.",
    body: "Upload a side view and compare before and after one drill round.",
    cta: "Analyze your swing",
    destinationUrl: "https://www.proswing.net",
    campaignId: "PRO_X_TRIAL_PLAYERS_US_202610",
    creativeId: "PRO_CASTING_X_V1",
    publishAt: "2026-10-09T13:00:00Z",
    priority: "p1",
    audience: "Players and coaches",
    creative: "Annotated still, elbow path arrow",
    objective: "Analysis start",
    sourceAsset: "Example analysis flow",
  }),
  post({
    contentId: "img-x-proof-01",
    appId: "imgsquash",
    platform: "x",
    contentType: "x-post",
    pillar: "proof",
    topic: "Size proof",
    hook: "Same photo, 78 percent smaller, no visible change at feed size.",
    body: "Drop an export in ImgSquash and compare bytes before uploading.",
    cta: "Try it",
    destinationUrl: "https://imgsquash.com",
    campaignId: "IMG_X_ACTIVATION_MAKERS_US_202610",
    creativeId: "IMG_BYTES_X_V1",
    publishAt: "2026-10-10T16:00:00Z",
    priority: "p2",
    audience: "Makers shipping images",
    creative: "Side-by-side with byte labels",
    objective: "Compression completed",
    sourceAsset: "Tool output screen",
  }),
  post({
    contentId: "syn-ig-carousel-01",
    appId: "synthetic-pics",
    platform: "instagram",
    contentType: "carousel",
    pillar: "comparison",
    topic: "Style comparison",
    hook: "Same prompt family, 3 directions. Which fits your wall?",
    body: "Swipe for warm, cool, and monochrome takes. Links to each artwork.",
    cta: "Explore the gallery",
    destinationUrl: "https://www.synthetic.pics",
    campaignId: "SYN_IG_DISCOVERY_ARTBUYERS_US_202610",
    creativeId: "SYN_STYLE_CAR_V1",
    publishAt: "2026-10-11T15:00:00Z",
    priority: "p1",
    audience: "Art browsers",
    creative: "3-card carousel, one style per card",
    objective: "Gallery visit",
    sourceAsset: "Gallery artworks",
  }),
  post({
    contentId: "aicl-ig-beforeafter-01",
    appId: "aicapturelab",
    platform: "instagram",
    contentType: "before-after",
    pillar: "proof",
    topic: "Background swap",
    hook: "Phone photo left. Studio look right.",
    body: "One input photo to clean product shot. See more transformations.",
    cta: "See the transformation",
    destinationUrl: "https://www.aicapturelab.com",
    campaignId: "LAB_IG_ACTIVATION_SELLERS_US_202610",
    creativeId: "LAB_SWAP_BA_V1",
    publishAt: "2026-10-12T23:00:00Z",
    priority: "p2",
    audience: "Sellers",
    creative: "Before/after same framing",
    objective: "Gallery view",
    sourceAsset: "Transformation gallery",
  }),
  post({
    contentId: "p3d-ig-reel-01",
    appId: "print3dmodels",
    platform: "instagram",
    contentType: "reel-concept",
    pillar: "product",
    topic: "Print detail",
    hook: "Watch the layer lines catch the light.",
    body: "Printed to order. Close-ups and scale on the product page.",
    cta: "Shop the print",
    destinationUrl: "https://www.print3dmodels.com",
    campaignId: "P3D_IG_PURCHASE_GIFTBUYERS_US_202610",
    creativeId: "P3D_DETAIL_REEL_V1",
    publishAt: "2026-10-13T16:00:00Z",
    priority: "p1",
    audience: "Gift buyers",
    creative: "10s rotating product concept",
    objective: "Product purchase",
    sourceAsset: "Product photos",
  }),
  post({
    contentId: "mix-fb-recipe-01",
    appId: "mixphd",
    platform: "facebook",
    contentType: "facebook-post",
    pillar: "how-to",
    topic: "Technique tip",
    hook: "Shaken vs stirred: shake citrus, stir spirit-only.",
    body: "One rule plus a recipe for each. My Bar finds what you can make tonight.",
    cta: "Read the recipe",
    destinationUrl: "https://www.mixphd.com",
    campaignId: "MIX_FB_TRAFFIC_HOMEBAR_US_202610",
    creativeId: "MIX_SHAKE_FB_V1",
    publishAt: "2026-10-14T21:00:00Z",
    priority: "p2",
    audience: "Home bartenders",
    creative: "Single shaker photo with rule overlay",
    objective: "Recipe visit",
    sourceAsset: "Recipe plus technique note",
  }),
  post({
    contentId: "sig-x-method-01",
    appId: "profitsignals",
    platform: "x",
    contentType: "x-post",
    pillar: "education",
    topic: "Research method",
    hook: "Before running research, write the decision it informs.",
    body: "One-sentence decision first. Then run the workflow.",
    cta: "Run the analysis",
    destinationUrl: "https://www.profitsignals.xyz",
    campaignId: "SIG_X_TRIAL_OPERATORS_US_202610",
    creativeId: "SIG_DECISION_X_V1",
    publishAt: "2026-10-15T13:00:00Z",
    priority: "p3",
    audience: "Operators",
    creative: "Text plus workflow screenshot",
    objective: "Research run",
    sourceAsset: "Workflow entry screen",
  }),
  post({
    contentId: "syn-pin-room-02",
    appId: "synthetic-pics",
    platform: "pinterest",
    contentType: "pin",
    pillar: "use-case",
    topic: "Room context",
    hook: "Small hallway? This vertical piece adds depth.",
    body: "See scale notes and matching pieces in the gallery.",
    cta: "Explore the gallery",
    destinationUrl: "https://www.synthetic.pics",
    campaignId: "SYN_PINT_DISCOVERY_ARTBUYERS_US_202610",
    creativeId: "SYN_HALL_PIN_V1",
    publishAt: "2026-10-16T14:00:00Z",
    priority: "p1",
    audience: "Decor seekers",
    creative: "Room mock plus artwork crop",
    objective: "Gallery visit",
    sourceAsset: "Artwork page",
  }),
  post({
    contentId: "pro-ig-drill-01",
    appId: "proswing",
    platform: "instagram",
    contentType: "reel-concept",
    pillar: "how-to",
    topic: "Drill demo",
    hook: "One tee drill for staying inside the ball.",
    body: "15 seconds. Film from the front, compare contact position.",
    cta: "Analyze your swing",
    destinationUrl: "https://www.proswing.net",
    campaignId: "PRO_IG_TRIAL_PLAYERS_US_202610",
    creativeId: "PRO_DRILL_REEL_V1",
    publishAt: "2026-10-17T15:00:00Z",
    priority: "p1",
    audience: "Players",
    creative: "Demo clip concept with freeze frame",
    objective: "Analysis start",
    sourceAsset: "Drill guide",
  }),
  post({
    contentId: "p3d-fb-gift-01",
    appId: "print3dmodels",
    platform: "facebook",
    contentType: "facebook-post",
    pillar: "use-case",
    topic: "Gift use case",
    hook: "Desk gift under 30 that is not a mug.",
    body: "Printed to order. See lead times on the product page.",
    cta: "Shop the print",
    destinationUrl: "https://www.print3dmodels.com",
    campaignId: "P3D_FB_PURCHASE_GIFTBUYERS_US_202610",
    creativeId: "P3D_GIFT_FB_V1",
    publishAt: "2026-10-18T17:00:00Z",
    priority: "p2",
    audience: "Gift buyers",
    creative: "Gift box plus product",
    objective: "Purchase",
    sourceAsset: "Product page",
  }),
  post({
    contentId: "mix-pin-seasonal-01",
    appId: "mixphd",
    platform: "pinterest",
    contentType: "pin",
    pillar: "discovery",
    topic: "Fall roundup",
    hook: "5 apple drinks for fall, from crisp to cozy.",
    body: "One grid linking to 5 recipes. Save the board for later.",
    cta: "Explore all 5",
    destinationUrl: "https://www.mixphd.com",
    campaignId: "MIX_PINT_TRAFFIC_HOMEBAR_US_202610",
    creativeId: "MIX_FALL_PIN_V1",
    publishAt: "2026-10-19T14:00:00Z",
    priority: "p1",
    audience: "Recipe explorers",
    creative: "5-thumbnail grid pin",
    objective: "Recipe visits",
    sourceAsset: "Recipe index",
  }),
  post({
    contentId: "aiceo-li-lesson-01",
    appId: "aiceo",
    platform: "linkedin",
    contentType: "linkedin-post",
    pillar: "insight",
    topic: "Operating lesson",
    hook: "AI pilots stall when no one owns the workflow after week 2.",
    body: "Name an owner, a weekly review, and one activation metric. That is the whole fix.",
    cta: "Learn more",
    destinationUrl: "https://aiceo.io",
    campaignId: "CEO_LI_DISCOVERY_FOUNDERS_US_202610",
    creativeId: "CEO_OWNER_LI_V1",
    publishAt: "2026-10-20T13:00:00Z",
    priority: "p3",
    audience: "Founders",
    creative: "Text post, no image needed",
    objective: "Site visit",
    sourceAsset: "Operating notes",
  }),
  post({
    contentId: "syn-ig-process-01",
    appId: "synthetic-pics",
    platform: "instagram",
    contentType: "carousel",
    pillar: "build",
    topic: "Process note",
    hook: "How this piece kept its grain at large sizes.",
    body: "Constraint, choice, and export note. Full piece in gallery.",
    cta: "See the result",
    destinationUrl: "https://www.synthetic.pics",
    campaignId: "SYN_IG_DISCOVERY_ARTBUYERS_US_202610",
    creativeId: "SYN_GRAIN_CAR_V1",
    publishAt: "2026-10-21T16:00:00Z",
    priority: "p2",
    audience: "Art followers",
    creative: "Detail crops plus settings note",
    objective: "Gallery visit",
    sourceAsset: "Process notes",
  }),
  post({
    contentId: "img-reddit-answer-01",
    appId: "imgsquash",
    platform: "reddit",
    contentType: "reddit-answer",
    pillar: "education",
    topic: "Format tip",
    hook: "For photos on the web: AVIF first, WebP fallback, JPEG last.",
    body: "Genuinely useful answer with steps. Link tool only as the compression step.",
    cta: "Try the compression step",
    destinationUrl: "https://imgsquash.com",
    campaignId: "IMG_RD_ACTIVATION_MAKERS_US_202610",
    creativeId: "IMG_AVIF_RD_V1",
    publishAt: "2026-10-22T14:00:00Z",
    priority: "p2",
    audience: "Web makers",
    creative: "No image, text answer with ordered steps",
    objective: "Tool trial",
    sourceAsset: "Format guide",
  }),
  post({
    contentId: "p3d-pin-detail-02",
    appId: "print3dmodels",
    platform: "pinterest",
    contentType: "pin",
    pillar: "proof",
    topic: "Detail close-up",
    hook: "Close-up: matte finish hides layer lines.",
    body: "See finish options and scale photos on the product page.",
    cta: "Shop the print",
    destinationUrl: "https://www.print3dmodels.com",
    campaignId: "P3D_PINT_PURCHASE_GIFTBUYERS_US_202610",
    creativeId: "P3D_MATTE_PIN_V1",
    publishAt: "2026-10-23T14:00:00Z",
    priority: "p1",
    audience: "Print buyers",
    creative: "Macro pin plus scale shot",
    objective: "Purchase",
    sourceAsset: "Product photos",
  }),
  post({
    contentId: "mix-x-mybar-01",
    appId: "mixphd",
    platform: "x",
    contentType: "x-post",
    pillar: "feature",
    topic: "My Bar match",
    hook: "Type 3 bottles you own. Get 5 drinks you can make now.",
    body: "My Bar matching demo. No signup to browse.",
    cta: "Read the recipe",
    destinationUrl: "https://www.mixphd.com",
    campaignId: "MIX_X_TRAFFIC_HOMEBAR_US_202610",
    creativeId: "MIX_MYBAR_X_V1",
    publishAt: "2026-10-24T16:00:00Z",
    priority: "p2",
    audience: "Home bartenders",
    creative: "Screen crop of My Bar results",
    objective: "Recipe visit",
    sourceAsset: "My Bar feature",
  }),
  post({
    contentId: "pro-yt-short-01",
    appId: "proswing",
    platform: "youtube-shorts",
    contentType: "short-demo-concept",
    pillar: "proof",
    topic: "Swing transformation concept",
    hook: "Two swings, one fix, side by side.",
    body: "Film front view. Compare hip rotation at contact.",
    cta: "Analyze your swing",
    destinationUrl: "https://www.proswing.net",
    campaignId: "PRO_YT_TRIAL_PLAYERS_US_202610",
    creativeId: "PRO_HIP_SHORT_V1",
    publishAt: "2026-10-25T14:00:00Z",
    priority: "p2",
    audience: "Players",
    creative: "12s split-screen concept",
    objective: "Analysis start",
    sourceAsset: "Example analysis",
  }),
  post({
    contentId: "syn-fb-drop-02",
    appId: "synthetic-pics",
    platform: "facebook",
    contentType: "facebook-post",
    pillar: "product",
    topic: "Weekend drop",
    hook: "Weekend drop: 3 warm minimal pieces.",
    body: "Short notes on each. Links to all three artworks.",
    cta: "Explore the gallery",
    destinationUrl: "https://www.synthetic.pics",
    campaignId: "SYN_FB_DISCOVERY_ARTBUYERS_US_202610",
    creativeId: "SYN_WARM_FB_V1",
    publishAt: "2026-10-26T17:00:00Z",
    priority: "p2",
    audience: "Art followers",
    creative: "3-up grid",
    objective: "Gallery visit",
    sourceAsset: "Gallery artworks",
  }),
  post({
    contentId: "aicl-pin-niche-01",
    appId: "aicapturelab",
    platform: "pinterest",
    contentType: "pin",
    pillar: "use-case",
    topic: "Niche showcase",
    hook: "Candle sellers: white sweep without a studio.",
    body: "One input photo to listing-ready shot. See candle examples.",
    cta: "See the transformation",
    destinationUrl: "https://www.aicapturelab.com",
    campaignId: "LAB_PINT_ACTIVATION_SELLERS_US_202610",
    creativeId: "LAB_CANDLE_PIN_V1",
    publishAt: "2026-10-27T14:00:00Z",
    priority: "p2",
    audience: "Candle sellers",
    creative: "Before/after pin for candles",
    objective: "Transformation view",
    sourceAsset: "Niche gallery",
  }),
  post({
    contentId: "p3d-x-oldnew-01",
    appId: "print3dmodels",
    platform: "x",
    contentType: "x-post",
    pillar: "comparison",
    topic: "Old vs new decor",
    hook: "Old way: mass vase. New way: printed piece in your color.",
    body: "Pick color at checkout. Printed to order.",
    cta: "Shop the print",
    destinationUrl: "https://www.print3dmodels.com",
    campaignId: "P3D_X_PURCHASE_GIFTBUYERS_US_202610",
    creativeId: "P3D_OLDNEW_X_V1",
    publishAt: "2026-10-28T16:00:00Z",
    priority: "p2",
    audience: "Decor buyers",
    creative: "Two-panel old vs new",
    objective: "Purchase",
    sourceAsset: "Product variants",
  }),
  post({
    contentId: "mix-ig-carousel-02",
    appId: "mixphd",
    platform: "instagram",
    contentType: "carousel",
    pillar: "education",
    topic: "Checklist",
    hook: "5-point home bar starter checklist.",
    body: "One essential per card with a recipe using it.",
    cta: "Read the recipe",
    destinationUrl: "https://www.mixphd.com",
    campaignId: "MIX_IG_TRAFFIC_HOMEBAR_US_202610",
    creativeId: "MIX_CHECK_CAR_V1",
    publishAt: "2026-10-29T16:00:00Z",
    priority: "p2",
    audience: "Beginners",
    creative: "5-card checklist carousel",
    objective: "Recipe visit",
    sourceAsset: "Starter guide",
  }),
  post({
    contentId: "syn-x-result-01",
    appId: "synthetic-pics",
    platform: "x",
    contentType: "x-post",
    pillar: "insight",
    topic: "Color note",
    hook: "Warm neutrals outperform cool blues for saves in our gallery.",
    body: "Observation from browsing patterns, not a rule. See warm pieces.",
    cta: "Explore the gallery",
    destinationUrl: "https://www.synthetic.pics",
    campaignId: "SYN_X_DISCOVERY_ARTBUYERS_US_202610",
    creativeId: "SYN_WARM_X_V1",
    publishAt: "2026-10-30T13:00:00Z",
    priority: "p3",
    audience: "Art browsers",
    creative: "Warm grid collage",
    objective: "Gallery visit",
    sourceAsset: "Gallery browsing",
  }),
  post({
    contentId: "pro-reddit-answer-01",
    appId: "proswing",
    platform: "reddit",
    contentType: "reddit-answer",
    pillar: "education",
    topic: "Community answer",
    hook: "Answer: drill for early extension.",
    body: "Useful drill steps first. Link analysis only if they ask for feedback.",
    cta: "See an example analysis",
    destinationUrl: "https://www.proswing.net",
    campaignId: "PRO_RD_TRIAL_PLAYERS_US_202610",
    creativeId: "PRO_EXTENSION_RD_V1",
    publishAt: "2026-10-31T14:00:00Z",
    priority: "p3",
    audience: "Community players",
    creative: "Text answer, no promo image",
    objective: "High-intent visit",
    sourceAsset: "Coaching note",
  }),
  post({
    contentId: "img-x-tip-02",
    appId: "imgsquash",
    platform: "x",
    contentType: "x-post",
    pillar: "how-to",
    topic: "Export tip",
    hook: "Export at 2000px max for hero images. Larger rarely helps.",
    body: "Resize before compressing. Compare bytes in one pass.",
    cta: "Try it",
    destinationUrl: "https://imgsquash.com",
    campaignId: "IMG_X_ACTIVATION_MAKERS_US_202610",
    creativeId: "IMG_EXPORT_X_V1",
    publishAt: "2026-11-01T16:00:00Z",
    priority: "p3",
    audience: "Makers",
    creative: "Settings crop with byte output",
    objective: "Compression completed",
    sourceAsset: "Tool guide",
  }),
  post({
    contentId: "p3d-ig-carousel-02",
    appId: "print3dmodels",
    platform: "instagram",
    contentType: "carousel",
    pillar: "discovery",
    topic: "Seasonal picks",
    hook: "3 cozy prints for fall shelves.",
    body: "Swipe for each with scale. Links to all three.",
    cta: "Shop the picks",
    destinationUrl: "https://www.print3dmodels.com",
    campaignId: "P3D_IG_PURCHASE_GIFTBUYERS_US_202610",
    creativeId: "P3D_FALL_CAR_V1",
    publishAt: "2026-11-02T15:00:00Z",
    priority: "p1",
    audience: "Gift buyers",
    creative: "Fall shelf styling carousel",
    objective: "Purchase",
    sourceAsset: "Product pages",
  }),
  post({
    contentId: "syn-pin-bridge-01",
    appId: "synthetic-pics",
    platform: "pinterest",
    contentType: "pin",
    pillar: "portfolio",
    topic: "Cross-portfolio bridge",
    hook: "Like this print? The 3D version lives in our sister shop.",
    body: "Part of the Pantaleone portfolio. One link to each shop.",
    cta: "Shop the companion",
    destinationUrl: "https://www.synthetic.pics",
    campaignId: "SYN_PINT_DISCOVERY_PORTFOLIO_US_202610",
    creativeId: "SYN_BRIDGE_PIN_V1",
    publishAt: "2026-11-03T14:00:00Z",
    priority: "p3",
    audience: "Portfolio explorers",
    creative: "Minimal two-brand card",
    objective: "Cross-portfolio discovery",
    sourceAsset: "Ecosystem links",
  }),
  post({
    contentId: "sig-li-hygiene-01",
    appId: "profitsignals",
    platform: "linkedin",
    contentType: "linkedin-post",
    pillar: "education",
    topic: "Data hygiene",
    hook: "Most research fails on inputs, not models.",
    body: "Checklist: source date, sample, and one disconfirming source. No performance claims.",
    cta: "Learn more",
    destinationUrl: "https://www.profitsignals.xyz",
    campaignId: "SIG_LI_DISCOVERY_OPERATORS_US_202610",
    creativeId: "SIG_HYGIENE_LI_V1",
    publishAt: "2026-11-04T13:00:00Z",
    priority: "p3",
    audience: "Operators",
    creative: "Checklist graphic",
    objective: "Site visit",
    sourceAsset: "Method note",
  }),
  post({
    contentId: "portfolio-x-01",
    appId: "pantaleone",
    platform: "x",
    contentType: "x-post",
    pillar: "portfolio",
    topic: "Ecosystem intro",
    hook: "One builder, 8 small tools. Each solves one job.",
    body: "Gallery, recipes, swing analysis, compression, prints, photo studio, and research.",
    cta: "Explore the apps",
    destinationUrl: "https://www.pantaleone.net/apps",
    campaignId: "PNT_X_DISCOVERY_GENERAL_US_202610",
    creativeId: "PNT_APPS_X_V1",
    publishAt: "2026-11-05T13:00:00Z",
    priority: "p3",
    audience: "General discovery",
    creative: "App grid",
    objective: "Portfolio discovery",
    sourceAsset: "Ecosystem registry",
  }),
  post({
    contentId: "syn-pin-evergreen-03",
    appId: "synthetic-pics",
    platform: "pinterest",
    contentType: "pin",
    pillar: "education",
    topic: "Sizing guide",
    hook: "What size print for an 8-foot wall?",
    body: "Simple sizing rule plus gallery pieces that fit. Save for later.",
    cta: "Explore the gallery",
    destinationUrl: "https://www.synthetic.pics",
    campaignId: "SYN_PINT_DISCOVERY_ARTBUYERS_US_202610",
    creativeId: "SYN_SIZE_PIN_V1",
    publishAt: "2026-11-06T14:00:00Z",
    priority: "p2",
    audience: "Decor seekers",
    creative: "Sizing diagram pin",
    objective: "Save and visit",
    sourceAsset: "Sizing guide",
  }),
];
