/**
 * 20+ reusable post frameworks. Each: hook, body, visual, CTA,
 * best platform, best category. Short, specific, useful, visual, actionable.
 */

export type PostFramework = {
  id: string;
  name: string;
  hook: string;
  bodyStructure: string;
  visual: string;
  cta: string;
  bestPlatform: string;
  bestCategory: string;
};

export const POST_FRAMEWORKS: PostFramework[] = [
  {
    id: "problem-solution",
    name: "Problem to Solution",
    hook: "Name the painful moment in 8 words.",
    bodyStructure: "Problem (1 line) -> fix (1 line) -> result (1 line)",
    visual: "Product UI or output showing the fix",
    cta: "Try it",
    bestPlatform: "x, instagram",
    bestCategory: "tool, analysis",
  },
  {
    id: "before-after",
    name: "Before to After",
    hook: "Left is before. Right is after.",
    bodyStructure: "Before state -> change made -> after state",
    visual: "Side-by-side before/after, same framing",
    cta: "See the result",
    bestPlatform: "instagram, pinterest, youtube-shorts",
    bestCategory: "visual, transformation",
  },
  {
    id: "did-you-know",
    name: "Did You Know Insight",
    hook: "One surprising fact from real usage.",
    bodyStructure: "Fact -> why it matters -> where to see it",
    visual: "Single annotated screenshot or crop",
    cta: "Learn more",
    bestPlatform: "x, facebook",
    bestCategory: "education",
  },
  {
    id: "three-mistakes",
    name: "3 Mistakes Fix",
    hook: "3 mistakes people make with X.",
    bodyStructure: "Mistake 1/2/3 -> better approach for each",
    visual: "Numbered carousel, one mistake per card",
    cta: "Try the better way",
    bestPlatform: "instagram, linkedin",
    bestCategory: "education, how-to",
  },
  {
    id: "one-tip-example",
    name: "One Tip Plus Example",
    hook: "One tip that saves 5 minutes.",
    bodyStructure: "Tip -> concrete example -> link to try",
    visual: "Close-up of the exact step",
    cta: "Try it",
    bestPlatform: "x, pinterest",
    bestCategory: "how-to",
  },
  {
    id: "input-output",
    name: "Input Transformation Output",
    hook: "Watch this input become this output.",
    bodyStructure: "Input -> transformation (1 step) -> output",
    visual: "5-15s screen capture concept or 3-frame carousel",
    cta: "Generate now",
    bestPlatform: "instagram, youtube-shorts, pinterest",
    bestCategory: "transformation",
  },
  {
    id: "question-answer",
    name: "Question Answer Product",
    hook: "Quote a real user question.",
    bodyStructure: "Question -> direct answer -> product path",
    visual: "Question as text card plus answer visual",
    cta: "See the answer in the app",
    bestPlatform: "reddit, x",
    bestCategory: "faq, support",
  },
  {
    id: "myth-reality",
    name: "Myth Reality",
    hook: "Myth: X. Reality: Y.",
    bodyStructure: "Myth -> evidence -> what to do instead",
    visual: "Two-panel myth vs reality",
    cta: "Learn more",
    bestPlatform: "linkedin, x",
    bestCategory: "insight",
  },
  {
    id: "use-case-demo",
    name: "Use Case Demo",
    hook: "For [specific person] doing [specific job].",
    bodyStructure: "Scenario -> demo -> outcome",
    visual: "Real product path, no mock UI",
    cta: "Start free",
    bestPlatform: "instagram, facebook",
    bestCategory: "use-case",
  },
  {
    id: "result-why",
    name: "Interesting Result Why",
    hook: "This result surprised us.",
    bodyStructure: "Result -> why it happened -> how to reproduce",
    visual: "Data visual or output grid",
    cta: "Explore the gallery",
    bestPlatform: "x, pinterest",
    bestCategory: "proof, discovery",
  },
  {
    id: "comparison-table",
    name: "Old Way New Way",
    hook: "Old way vs new way.",
    bodyStructure: "Old steps (slow) -> new steps (fast) -> time saved",
    visual: "Two-column comparison card",
    cta: "Try the new way",
    bestPlatform: "linkedin, x",
    bestCategory: "comparison",
  },
  {
    id: "feature-context",
    name: "One Feature In Context",
    hook: "One feature, one job.",
    bodyStructure: "When X happens -> use this -> you get Y",
    visual: "Single feature highlighted in real UI",
    cta: "Try it",
    bestPlatform: "x, instagram",
    bestCategory: "feature",
  },
  {
    id: "drop-showcase",
    name: "Drop Showcase",
    hook: "New: [name] is live.",
    bodyStructure: "What it is -> who it fits -> where to find it",
    visual: "Hero visual of the new item",
    cta: "Shop the product",
    bestPlatform: "pinterest, instagram",
    bestCategory: "discovery, product",
  },
  {
    id: "process-note",
    name: "Build Note",
    hook: "How we made X.",
    bodyStructure: "Constraint -> choice -> lesson",
    visual: "Work-in-progress or detail shot",
    cta: "See the result",
    bestPlatform: "x, linkedin",
    bestCategory: "build",
  },
  {
    id: "checklist-post",
    name: "Checklist",
    hook: "5-point checklist for X.",
    bodyStructure: "Checklist 1-5, each one line",
    visual: "Carousel checklist",
    cta: "Save this",
    bestPlatform: "instagram, pinterest",
    bestCategory: "education",
  },
  {
    id: "mistake-fix-single",
    name: "Single Mistake Fix",
    hook: "Stop doing X. Do Y.",
    bodyStructure: "Wrong pattern -> right pattern -> proof",
    visual: "Annotated correction",
    cta: "Try the fix",
    bestPlatform: "instagram, youtube-shorts",
    bestCategory: "education",
  },
  {
    id: "roundup-post",
    name: "Roundup",
    hook: "5 best X for [occasion].",
    bodyStructure: "5 items, one line each, links to each",
    visual: "Grid of 5 thumbnails",
    cta: "Explore all 5",
    bestPlatform: "pinterest, facebook",
    bestCategory: "discovery",
  },
  {
    id: " faq-answer",
    name: "FAQ Answer",
    hook: "Most asked: [question].",
    bodyStructure: "Answer in 2 sentences -> link to source",
    visual: "Product section answering it",
    cta: "Read more",
    bestPlatform: "reddit, facebook",
    bestCategory: "education",
  },
  {
    id: "stateless-proof",
    name: "Proof Without Hype",
    hook: "Here is what changed, measured.",
    bodyStructure: "Setup -> measured change -> method note",
    visual: "Before/after with labels, no invented numbers",
    cta: "See how",
    bestPlatform: "x, linkedin",
    bestCategory: "proof",
  },
  {
    id: "portfolio-bridge",
    name: "Portfolio Bridge",
    hook: "Built another tool for this.",
    bodyStructure: "Problem in app A -> companion in app B -> link",
    visual: "Both product marks, minimal",
    cta: "Try the companion",
    bestPlatform: "x, facebook",
    bestCategory: "portfolio",
  },
  {
    id: "seasonal-angle",
    name: "Seasonal Angle",
    hook: "For [season/event]: [pick].",
    bodyStructure: "Occasion -> 3 fits -> links",
    visual: "Seasonal grid",
    cta: "Shop the picks",
    bestPlatform: "pinterest, instagram",
    bestCategory: "discovery",
  },
  {
    id: "experiment-teaser",
    name: "Experiment Teaser",
    hook: "Testing: [idea]. Want it?",
    bodyStructure: "Hypothesis -> early look -> ask for signal",
    visual: "Draft or prototype, labeled as test",
    cta: "Tell us if useful",
    bestPlatform: "x",
    bestCategory: "experiment",
  },
];
